from rest_framework import routers
from ..views import *  # noqa

router = routers.SimpleRouter()

router.register(r'example',
                ExampleViewSet,
                'Example')
router.register(r'surface',
                SurfaceViewSet,
                'Surface')
router.register(r'LOINC_48002_0_answerlist',
                Loinc480020AnswerlistViewSet,
                'Loinc480020Answerlist')
router.register(r'LOINC_48019_4_answerlist',
                Loinc480194AnswerlistViewSet,
                'Loinc480194Answerlist')
router.register(r'LOINC_53034_5_answerlist',
                Loinc530345AnswerlistViewSet,
                'Loinc530345Answerlist')
router.register(r'abstract_types',
                AbstractTypesViewSet,
                'AbstractTypes')
router.register(r'account_status',
                AccountStatusViewSet,
                'AccountStatus')
router.register(r'action_behavior_type',
                ActionBehaviorTypeViewSet,
                'ActionBehaviorType')
router.register(r'action_cardinality_behavior',
                ActionCardinalityBehaviorViewSet,
                'ActionCardinalityBehavior')
router.register(r'action_grouping_behavior',
                ActionGroupingBehaviorViewSet,
                'ActionGroupingBehavior')
router.register(r'action_participant_type',
                ActionParticipantTypeViewSet,
                'ActionParticipantType')
router.register(r'action_precheck_behavior',
                ActionPrecheckBehaviorViewSet,
                'ActionPrecheckBehavior')
router.register(r'action_relationship_anchor',
                ActionRelationshipAnchorViewSet,
                'ActionRelationshipAnchor')
router.register(r'action_relationship_type',
                ActionRelationshipTypeViewSet,
                'ActionRelationshipType')
router.register(r'action_required_behavior',
                ActionRequiredBehaviorViewSet,
                'ActionRequiredBehavior')
router.register(r'action_selection_behavior',
                ActionSelectionBehaviorViewSet,
                'ActionSelectionBehavior')
router.register(r'action_type',
                ActionTypeViewSet,
                'ActionType')
router.register(r'actionlist',
                ActionlistViewSet,
                'Actionlist')
router.register(r'activity_definition_category',
                ActivityDefinitionCategoryViewSet,
                'ActivityDefinitionCategory')
router.register(r'activity_participant_type',
                ActivityParticipantTypeViewSet,
                'ActivityParticipantType')
router.register(r'additionalmaterials',
                AdditionalmaterialsViewSet,
                'Additionalmaterials')
router.register(r'address_type',
                AddressTypeViewSet,
                'AddressType')
router.register(r'address_use',
                AddressUseViewSet,
                'AddressUse')
router.register(r'adjudication',
                AdjudicationViewSet,
                'Adjudication')
router.register(r'adjudication_error',
                AdjudicationErrorViewSet,
                'AdjudicationError')
router.register(r'adjudication_reason',
                AdjudicationReasonViewSet,
                'AdjudicationReason')
router.register(r'administrative_gender',
                AdministrativeGenderViewSet,
                'AdministrativeGender')
router.register(r'encounter_admit_source',
                EncounterAdmitSourceViewSet,
                'EncounterAdmitSource')
router.register(r'allergy_intolerance_category',
                AllergyIntoleranceCategoryViewSet,
                'AllergyIntoleranceCategory')
router.register(r'allergy_intolerance_criticality',
                AllergyIntoleranceCriticalityViewSet,
                'AllergyIntoleranceCriticality')
router.register(r'allergy_intolerance_status',
                AllergyIntoleranceStatusViewSet,
                'AllergyIntoleranceStatus')
router.register(r'allergy_intolerance_type',
                AllergyIntoleranceTypeViewSet,
                'AllergyIntoleranceType')
router.register(r'animal_breeds',
                AnimalBreedsViewSet,
                'AnimalBreeds')
router.register(r'animal_genderstatus',
                AnimalGenderstatusViewSet,
                'AnimalGenderstatus')
router.register(r'animal_species',
                AnimalSpeciesViewSet,
                'AnimalSpecies')
router.register(r'appointmentstatus',
                AppointmentstatusViewSet,
                'Appointmentstatus')
router.register(r'assert_direction_codes',
                AssertDirectionCodesViewSet,
                'AssertDirectionCodes')
router.register(r'assert_operator_codes',
                AssertOperatorCodesViewSet,
                'AssertOperatorCodes')
router.register(r'assert_response_code_types',
                AssertResponseCodeTypesViewSet,
                'AssertResponseCodeTypes')
router.register(r'audit_event_action',
                AuditEventActionViewSet,
                'AuditEventAction')
router.register(r'audit_event_outcome',
                AuditEventOutcomeViewSet,
                'AuditEventOutcome')
router.register(r'audit_event_type',
                AuditEventTypeViewSet,
                'AuditEventType')
router.register(r'basic_resource_type',
                BasicResourceTypeViewSet,
                'BasicResourceType')
router.register(r'benefit_category',
                BenefitCategoryViewSet,
                'BenefitCategory')
router.register(r'benefit_network',
                BenefitNetworkViewSet,
                'BenefitNetwork')
router.register(r'benefit_subcategory',
                BenefitSubcategoryViewSet,
                'BenefitSubcategory')
router.register(r'benefit_term',
                BenefitTermViewSet,
                'BenefitTerm')
router.register(r'benefit_type',
                BenefitTypeViewSet,
                'BenefitType')
router.register(r'benefit_unit',
                BenefitUnitViewSet,
                'BenefitUnit')
router.register(r'binding_strength',
                BindingStrengthViewSet,
                'BindingStrength')
router.register(r'bundle_type',
                BundleTypeViewSet,
                'BundleType')
router.register(r'cardinality_behavior',
                CardinalityBehaviorViewSet,
                'CardinalityBehavior')
router.register(r'care_plan_activity_category',
                CarePlanActivityCategoryViewSet,
                'CarePlanActivityCategory')
router.register(r'care_plan_activity_status',
                CarePlanActivityStatusViewSet,
                'CarePlanActivityStatus')
router.register(r'care_plan_relationship',
                CarePlanRelationshipViewSet,
                'CarePlanRelationship')
router.register(r'care_plan_status',
                CarePlanStatusViewSet,
                'CarePlanStatus')
router.register(r'cds_rule_action_type',
                CdsRuleActionTypeViewSet,
                'CdsRuleActionType')
router.register(r'cds_rule_participant',
                CdsRuleParticipantViewSet,
                'CdsRuleParticipant')
router.register(r'cds_rule_trigger_type',
                CdsRuleTriggerTypeViewSet,
                'CdsRuleTriggerType')
router.register(r'choice_list_orientation',
                ChoiceListOrientationViewSet,
                'ChoiceListOrientation')
router.register(r'chromosome_human',
                ChromosomeHumanViewSet,
                'ChromosomeHuman')
router.register(r'claim_exception',
                ClaimExceptionViewSet,
                'ClaimException')
router.register(r'claim_type_link',
                ClaimTypeLinkViewSet,
                'ClaimTypeLink')
router.register(r'claim_type_link2',
                ClaimTypeLink2ViewSet,
                'ClaimTypeLink2')
router.register(r'claim_use_link',
                ClaimUseLinkViewSet,
                'ClaimUseLink')
router.register(r'claim_careteamrole',
                ClaimCareteamroleViewSet,
                'ClaimCareteamrole')
router.register(r'claim_informationcategory',
                ClaimInformationcategoryViewSet,
                'ClaimInformationcategory')
router.register(r'classification_or_context',
                ClassificationOrContextViewSet,
                'ClassificationOrContext')
router.register(r'clinical_impression_status',
                ClinicalImpressionStatusViewSet,
                'ClinicalImpressionStatus')
router.register(r'content_mode',
                ContentModeViewSet,
                'ContentMode')
router.register(r'communication_request_status',
                CommunicationRequestStatusViewSet,
                'CommunicationRequestStatus')
router.register(r'communication_status',
                CommunicationStatusViewSet,
                'CommunicationStatus')
router.register(r'compartment_type',
                CompartmentTypeViewSet,
                'CompartmentType')
router.register(r'composition_attestation_mode',
                CompositionAttestationModeViewSet,
                'CompositionAttestationMode')
router.register(r'composition_status',
                CompositionStatusViewSet,
                'CompositionStatus')
router.register(r'concept_map_equivalence',
                ConceptMapEquivalenceViewSet,
                'ConceptMapEquivalence')
router.register(r'concept_properties',
                ConceptPropertiesViewSet,
                'ConceptProperties')
router.register(r'concept_property_type',
                ConceptPropertyTypeViewSet,
                'ConceptPropertyType')
router.register(r'condition_category',
                ConditionCategoryViewSet,
                'ConditionCategory')
router.register(r'condition_clinical',
                ConditionClinicalViewSet,
                'ConditionClinical')
router.register(r'condition_state',
                ConditionStateViewSet,
                'ConditionState')
router.register(r'condition_ver_status',
                ConditionVerStatusViewSet,
                'ConditionVerStatus')
router.register(r'conditional_delete_status',
                ConditionalDeleteStatusViewSet,
                'ConditionalDeleteStatus')
router.register(r'conformance_expectation',
                ConformanceExpectationViewSet,
                'ConformanceExpectation')
router.register(r'conformance_resource_status',
                ConformanceResourceStatusViewSet,
                'ConformanceResourceStatus')
router.register(r'conformance_statement_kind',
                ConformanceStatementKindViewSet,
                'ConformanceStatementKind')
router.register(r'consent_data_meaning',
                ConsentDataMeaningViewSet,
                'ConsentDataMeaning')
router.register(r'consent_except_type',
                ConsentExceptTypeViewSet,
                'ConsentExceptType')
router.register(r'consent_status',
                ConsentStatusViewSet,
                'ConsentStatus')
router.register(r'consent_action',
                ConsentActionViewSet,
                'ConsentAction')
router.register(r'consent_category',
                ConsentCategoryViewSet,
                'ConsentCategory')
router.register(r'constraint_severity',
                ConstraintSeverityViewSet,
                'ConstraintSeverity')
router.register(r'contact_point_system',
                ContactPointSystemViewSet,
                'ContactPointSystem')
router.register(r'contact_point_use',
                ContactPointUseViewSet,
                'ContactPointUse')
router.register(r'contactentity_type',
                ContactentityTypeViewSet,
                'ContactentityType')
router.register(r'content_type',
                ContentTypeViewSet,
                'ContentType')
router.register(r'contract_subtype',
                ContractSubtypeViewSet,
                'ContractSubtype')
router.register(r'contract_term_subtype',
                ContractTermSubtypeViewSet,
                'ContractTermSubtype')
router.register(r'contract_term_type',
                ContractTermTypeViewSet,
                'ContractTermType')
router.register(r'contract_type',
                ContractTypeViewSet,
                'ContractType')
router.register(r'copy_number_event',
                CopyNumberEventViewSet,
                'CopyNumberEvent')
router.register(r'coverage_exception',
                CoverageExceptionViewSet,
                'CoverageException')
router.register(r'dWebType',
                DwebtypeViewSet,
                'Dwebtype')
router.register(r'data_absent_reason',
                DataAbsentReasonViewSet,
                'DataAbsentReason')
router.register(r'data_types',
                DataTypesViewSet,
                'DataTypes')
router.register(r'dataelement_stringency',
                DataelementStringencyViewSet,
                'DataelementStringency')
router.register(r'days_of_week',
                DaysOfWeekViewSet,
                'DaysOfWeek')
router.register(r'detectedissue_severity',
                DetectedissueSeverityViewSet,
                'DetectedissueSeverity')
router.register(r'device_action',
                DeviceActionViewSet,
                'DeviceAction')
router.register(r'device_use_request_priority',
                DeviceUseRequestPriorityViewSet,
                'DeviceUseRequestPriority')
router.register(r'device_use_request_status',
                DeviceUseRequestStatusViewSet,
                'DeviceUseRequestStatus')
router.register(r'devicestatus',
                DevicestatusViewSet,
                'Devicestatus')
router.register(r'diagnostic_order_priority',
                DiagnosticOrderPriorityViewSet,
                'DiagnosticOrderPriority')
router.register(r'diagnostic_order_status',
                DiagnosticOrderStatusViewSet,
                'DiagnosticOrderStatus')
router.register(r'diagnostic_report_status',
                DiagnosticReportStatusViewSet,
                'DiagnosticReportStatus')
router.register(r'encounter_diet',
                EncounterDietViewSet,
                'EncounterDiet')
router.register(r'digital_media_type',
                DigitalMediaTypeViewSet,
                'DigitalMediaType')
router.register(r'encounter_discharge_disposition',
                EncounterDischargeDispositionViewSet,
                'EncounterDischargeDisposition')
router.register(r'document_mode',
                DocumentModeViewSet,
                'DocumentMode')
router.register(r'document_reference_status',
                DocumentReferenceStatusViewSet,
                'DocumentReferenceStatus')
router.register(r'document_relationship_type',
                DocumentRelationshipTypeViewSet,
                'DocumentRelationshipType')
router.register(r'encounter_location_status',
                EncounterLocationStatusViewSet,
                'EncounterLocationStatus')
router.register(r'encounter_priority',
                EncounterPriorityViewSet,
                'EncounterPriority')
router.register(r'encounter_special_arrangements',
                EncounterSpecialArrangementsViewSet,
                'EncounterSpecialArrangements')
router.register(r'encounter_state',
                EncounterStateViewSet,
                'EncounterState')
router.register(r'encounter_type',
                EncounterTypeViewSet,
                'EncounterType')
router.register(r'endpoint_status',
                EndpointStatusViewSet,
                'EndpointStatus')
router.register(r'entformula_additive',
                EntformulaAdditiveViewSet,
                'EntformulaAdditive')
router.register(r'episode_of_care_status',
                EpisodeOfCareStatusViewSet,
                'EpisodeOfCareStatus')
router.register(r'service_uscls',
                ServiceUsclsViewSet,
                'ServiceUscls')
router.register(r'fm_itemtype',
                FmItemtypeViewSet,
                'FmItemtype')
router.register(r'occurrence_codes',
                OccurrenceCodesViewSet,
                'OccurrenceCodes')
router.register(r'occurrence_span_codes',
                OccurrenceSpanCodesViewSet,
                'OccurrenceSpanCodes')
router.register(r'claim_subtype',
                ClaimSubtypeViewSet,
                'ClaimSubtype')
router.register(r'value_codes',
                ValueCodesViewSet,
                'ValueCodes')
router.register(r'ex_diagnosisrelatedgroup',
                ExDiagnosisrelatedgroupViewSet,
                'ExDiagnosisrelatedgroup')
router.register(r'ex_diagnosistype',
                ExDiagnosistypeViewSet,
                'ExDiagnosistype')
router.register(r'teeth',
                TeethViewSet,
                'Teeth')
router.register(r'ex_onsettype',
                ExOnsettypeViewSet,
                'ExOnsettype')
router.register(r'oral_prosthodontic_material',
                OralProsthodonticMaterialViewSet,
                'OralProsthodonticMaterial')
router.register(r'ex_paymenttype',
                ExPaymenttypeViewSet,
                'ExPaymenttype')
router.register(r'service_pharmacy',
                ServicePharmacyViewSet,
                'ServicePharmacy')
router.register(r'ex_program_code',
                ExProgramCodeViewSet,
                'ExProgramCode')
router.register(r'provider_qualification',
                ProviderQualificationViewSet,
                'ProviderQualification')
router.register(r'related_claim_relationship',
                RelatedClaimRelationshipViewSet,
                'RelatedClaimRelationship')
router.register(r'service_modifiers',
                ServiceModifiersViewSet,
                'ServiceModifiers')
router.register(r'service_place',
                ServicePlaceViewSet,
                'ServicePlace')
router.register(r'service_product',
                ServiceProductViewSet,
                'ServiceProduct')
router.register(r'tooth',
                ToothViewSet,
                'Tooth')
router.register(r'udi',
                UdiViewSet,
                'Udi')
router.register(r'vision_product',
                VisionProductViewSet,
                'VisionProduct')
router.register(r'extension_context',
                ExtensionContextViewSet,
                'ExtensionContext')
router.register(r'filter_operator',
                FilterOperatorViewSet,
                'FilterOperator')
router.register(r'flag_category',
                FlagCategoryViewSet,
                'FlagCategory')
router.register(r'flag_priority',
                FlagPriorityViewSet,
                'FlagPriority')
router.register(r'flag_status',
                FlagStatusViewSet,
                'FlagStatus')
router.register(r'fm_conditions',
                FmConditionsViewSet,
                'FmConditions')
router.register(r'forms',
                FormsViewSet,
                'Forms')
router.register(r'fundsreserve',
                FundsreserveViewSet,
                'Fundsreserve')
router.register(r'goal_acceptance_status',
                GoalAcceptanceStatusViewSet,
                'GoalAcceptanceStatus')
router.register(r'goal_category',
                GoalCategoryViewSet,
                'GoalCategory')
router.register(r'goal_priority',
                GoalPriorityViewSet,
                'GoalPriority')
router.register(r'goal_relationship_type',
                GoalRelationshipTypeViewSet,
                'GoalRelationshipType')
router.register(r'goal_status',
                GoalStatusViewSet,
                'GoalStatus')
router.register(r'goal_status_reason',
                GoalStatusReasonViewSet,
                'GoalStatusReason')
router.register(r'group_type',
                GroupTypeViewSet,
                'GroupType')
router.register(r'grouping_behavior',
                GroupingBehaviorViewSet,
                'GroupingBehavior')
router.register(r'guidance_response_status',
                GuidanceResponseStatusViewSet,
                'GuidanceResponseStatus')
router.register(r'guide_dependency_type',
                GuideDependencyTypeViewSet,
                'GuideDependencyType')
router.register(r'guide_page_kind',
                GuidePageKindViewSet,
                'GuidePageKind')
router.register(r'history_status',
                HistoryStatusViewSet,
                'HistoryStatus')
router.register(r'http_verb',
                HttpVerbViewSet,
                'HttpVerb')
router.register(r'identifier_type',
                IdentifierTypeViewSet,
                'IdentifierType')
router.register(r'identifier_use',
                IdentifierUseViewSet,
                'IdentifierUse')
router.register(r'identity_assuranceLevel',
                IdentityAssurancelevelViewSet,
                'IdentityAssurancelevel')
router.register(r'immunization_recommendation_date_criterion',
                ImmunizationRecommendationDateCriterionViewSet,
                'ImmunizationRecommendationDateCriterion')
router.register(r'immunization_recommendation_status',
                ImmunizationRecommendationStatusViewSet,
                'ImmunizationRecommendationStatus')
router.register(r'intervention',
                InterventionViewSet,
                'Intervention')
router.register(r'issue_severity',
                IssueSeverityViewSet,
                'IssueSeverity')
router.register(r'issue_type',
                IssueTypeViewSet,
                'IssueType')
router.register(r'item_type',
                ItemTypeViewSet,
                'ItemType')
router.register(r'link_type',
                LinkTypeViewSet,
                'LinkType')
router.register(r'linkage_type',
                LinkageTypeViewSet,
                'LinkageType')
router.register(r'list_empty_reason',
                ListEmptyReasonViewSet,
                'ListEmptyReason')
router.register(r'list_example_codes',
                ListExampleCodesViewSet,
                'ListExampleCodes')
router.register(r'list_mode',
                ListModeViewSet,
                'ListMode')
router.register(r'list_order',
                ListOrderViewSet,
                'ListOrder')
router.register(r'list_status',
                ListStatusViewSet,
                'ListStatus')
router.register(r'location_mode',
                LocationModeViewSet,
                'LocationMode')
router.register(r'location_physical_type',
                LocationPhysicalTypeViewSet,
                'LocationPhysicalType')
router.register(r'location_status',
                LocationStatusViewSet,
                'LocationStatus')
router.register(r'map_context_type',
                MapContextTypeViewSet,
                'MapContextType')
router.register(r'map_input_mode',
                MapInputModeViewSet,
                'MapInputMode')
router.register(r'map_list_mode',
                MapListModeViewSet,
                'MapListMode')
router.register(r'map_model_mode',
                MapModelModeViewSet,
                'MapModelMode')
router.register(r'map_transform',
                MapTransformViewSet,
                'MapTransform')
router.register(r'marital_status',
                MaritalStatusViewSet,
                'MaritalStatus')
router.register(r'match_grade',
                MatchGradeViewSet,
                'MatchGrade')
router.register(r'measure_data_usage',
                MeasureDataUsageViewSet,
                'MeasureDataUsage')
router.register(r'measure_population',
                MeasurePopulationViewSet,
                'MeasurePopulation')
router.register(r'measure_report_status',
                MeasureReportStatusViewSet,
                'MeasureReportStatus')
router.register(r'measure_report_type',
                MeasureReportTypeViewSet,
                'MeasureReportType')
router.register(r'measure_scoring',
                MeasureScoringViewSet,
                'MeasureScoring')
router.register(r'measure_type',
                MeasureTypeViewSet,
                'MeasureType')
router.register(r'measurement_principle',
                MeasurementPrincipleViewSet,
                'MeasurementPrinciple')
router.register(r'digital_media_subtype',
                DigitalMediaSubtypeViewSet,
                'DigitalMediaSubtype')
router.register(r'medication_admin_status',
                MedicationAdminStatusViewSet,
                'MedicationAdminStatus')
router.register(r'medication_dispense_status',
                MedicationDispenseStatusViewSet,
                'MedicationDispenseStatus')
router.register(r'medication_order_status',
                MedicationOrderStatusViewSet,
                'MedicationOrderStatus')
router.register(r'medication_statement_status',
                MedicationStatementStatusViewSet,
                'MedicationStatementStatus')
router.register(r'message_conformance_event_mode',
                MessageConformanceEventModeViewSet,
                'MessageConformanceEventMode')
router.register(r'message_events',
                MessageEventsViewSet,
                'MessageEvents')
router.register(r'message_reason_encounter',
                MessageReasonEncounterViewSet,
                'MessageReasonEncounter')
router.register(r'message_significance_category',
                MessageSignificanceCategoryViewSet,
                'MessageSignificanceCategory')
router.register(r'message_transport',
                MessageTransportViewSet,
                'MessageTransport')
router.register(r'metric_calibration_state',
                MetricCalibrationStateViewSet,
                'MetricCalibrationState')
router.register(r'metric_calibration_type',
                MetricCalibrationTypeViewSet,
                'MetricCalibrationType')
router.register(r'metric_category',
                MetricCategoryViewSet,
                'MetricCategory')
router.register(r'metric_color',
                MetricColorViewSet,
                'MetricColor')
router.register(r'metric_operational_status',
                MetricOperationalStatusViewSet,
                'MetricOperationalStatus')
router.register(r'missing_tooth_reason',
                MissingToothReasonViewSet,
                'MissingToothReason')
router.register(r'claim_modifiers',
                ClaimModifiersViewSet,
                'ClaimModifiers')
router.register(r'module_metadata_contributor',
                ModuleMetadataContributorViewSet,
                'ModuleMetadataContributor')
router.register(r'module_metadata_focus_type',
                ModuleMetadataFocusTypeViewSet,
                'ModuleMetadataFocusType')
router.register(r'module_metadata_resource_type',
                ModuleMetadataResourceTypeViewSet,
                'ModuleMetadataResourceType')
router.register(r'module_metadata_status',
                ModuleMetadataStatusViewSet,
                'ModuleMetadataStatus')
router.register(r'module_metadata_type',
                ModuleMetadataTypeViewSet,
                'ModuleMetadataType')
router.register(r'name_use',
                NameUseViewSet,
                'NameUse')
router.register(r'namingsystem_identifier_type',
                NamingsystemIdentifierTypeViewSet,
                'NamingsystemIdentifierType')
router.register(r'namingsystem_type',
                NamingsystemTypeViewSet,
                'NamingsystemType')
router.register(r'narrative_status',
                NarrativeStatusViewSet,
                'NarrativeStatus')
router.register(r'network_type',
                NetworkTypeViewSet,
                'NetworkType')
router.register(r'note_type',
                NoteTypeViewSet,
                'NoteType')
router.register(r'nutrition_order_status',
                NutritionOrderStatusViewSet,
                'NutritionOrderStatus')
router.register(r'object_lifecycle',
                ObjectLifecycleViewSet,
                'ObjectLifecycle')
router.register(r'object_role',
                ObjectRoleViewSet,
                'ObjectRole')
router.register(r'object_type',
                ObjectTypeViewSet,
                'ObjectType')
router.register(r'observation_category',
                ObservationCategoryViewSet,
                'ObservationCategory')
router.register(r'observation_paramcode',
                ObservationParamcodeViewSet,
                'ObservationParamcode')
router.register(r'observation_relationshiptypes',
                ObservationRelationshiptypesViewSet,
                'ObservationRelationshiptypes')
router.register(r'observation_status',
                ObservationStatusViewSet,
                'ObservationStatus')
router.register(r'operation_kind',
                OperationKindViewSet,
                'OperationKind')
router.register(r'operation_outcome',
                OperationOutcomeViewSet,
                'OperationOutcome')
router.register(r'operation_parameter_use',
                OperationParameterUseViewSet,
                'OperationParameterUse')
router.register(r'order_set_item_type',
                OrderSetItemTypeViewSet,
                'OrderSetItemType')
router.register(r'order_set_participant',
                OrderSetParticipantViewSet,
                'OrderSetParticipant')
router.register(r'order_status',
                OrderStatusViewSet,
                'OrderStatus')
router.register(r'organization_type',
                OrganizationTypeViewSet,
                'OrganizationType')
router.register(r'encounter_participant_type',
                EncounterParticipantTypeViewSet,
                'EncounterParticipantType')
router.register(r'participantrequired',
                ParticipantrequiredViewSet,
                'Participantrequired')
router.register(r'participationstatus',
                ParticipationstatusViewSet,
                'Participationstatus')
router.register(r'patient_contact_relationship',
                PatientContactRelationshipViewSet,
                'PatientContactRelationship')
router.register(r'patient_mpi_match',
                PatientMpiMatchViewSet,
                'PatientMpiMatch')
router.register(r'payeetype',
                PayeetypeViewSet,
                'Payeetype')
router.register(r'payment_adjustment_reason',
                PaymentAdjustmentReasonViewSet,
                'PaymentAdjustmentReason')
router.register(r'payment_type',
                PaymentTypeViewSet,
                'PaymentType')
router.register(r'payment_status',
                PaymentStatusViewSet,
                'PaymentStatus')
router.register(r'planaction_behavior_type',
                PlanactionBehaviorTypeViewSet,
                'PlanactionBehaviorType')
router.register(r'planaction_relationship_anchor',
                PlanactionRelationshipAnchorViewSet,
                'PlanactionRelationshipAnchor')
router.register(r'planaction_relationship_type',
                PlanactionRelationshipTypeViewSet,
                'PlanactionRelationshipType')
router.register(r'planaction_type',
                PlanactionTypeViewSet,
                'PlanactionType')
router.register(r'practitioner_role',
                PractitionerRoleViewSet,
                'PractitionerRole')
router.register(r'practitioner_specialty',
                PractitionerSpecialtyViewSet,
                'PractitionerSpecialty')
router.register(r'precheck_behavior',
                PrecheckBehaviorViewSet,
                'PrecheckBehavior')
router.register(r'procedure_progress_status_codes',
                ProcedureProgressStatusCodesViewSet,
                'ProcedureProgressStatusCodes')
router.register(r'procedure_relationship_type',
                ProcedureRelationshipTypeViewSet,
                'ProcedureRelationshipType')
router.register(r'procedure_request_priority',
                ProcedureRequestPriorityViewSet,
                'ProcedureRequestPriority')
router.register(r'procedure_request_status',
                ProcedureRequestStatusViewSet,
                'ProcedureRequestStatus')
router.register(r'procedure_status',
                ProcedureStatusViewSet,
                'ProcedureStatus')
router.register(r'process_outcome',
                ProcessOutcomeViewSet,
                'ProcessOutcome')
router.register(r'process_priority',
                ProcessPriorityViewSet,
                'ProcessPriority')
router.register(r'property_representation',
                PropertyRepresentationViewSet,
                'PropertyRepresentation')
router.register(r'protocol_activity_category',
                ProtocolActivityCategoryViewSet,
                'ProtocolActivityCategory')
router.register(r'protocol_status',
                ProtocolStatusViewSet,
                'ProtocolStatus')
router.register(r'protocol_type',
                ProtocolTypeViewSet,
                'ProtocolType')
router.register(r'provenance_entity_role',
                ProvenanceEntityRoleViewSet,
                'ProvenanceEntityRole')
router.register(r'provenance_agent_role',
                ProvenanceAgentRoleViewSet,
                'ProvenanceAgentRole')
router.register(r'provenance_agent_type',
                ProvenanceAgentTypeViewSet,
                'ProvenanceAgentType')
router.register(r'quantity_comparator',
                QuantityComparatorViewSet,
                'QuantityComparator')
router.register(r'question_max_occurs',
                QuestionMaxOccursViewSet,
                'QuestionMaxOccurs')
router.register(r'questionnaire_answers_status',
                QuestionnaireAnswersStatusViewSet,
                'QuestionnaireAnswersStatus')
router.register(r'questionnaire_display_category',
                QuestionnaireDisplayCategoryViewSet,
                'QuestionnaireDisplayCategory')
router.register(r'questionnaire_item_control',
                QuestionnaireItemControlViewSet,
                'QuestionnaireItemControl')
router.register(r'questionnaire_status',
                QuestionnaireStatusViewSet,
                'QuestionnaireStatus')
router.register(r'reaction_event_certainty',
                ReactionEventCertaintyViewSet,
                'ReactionEventCertainty')
router.register(r'reaction_event_severity',
                ReactionEventSeverityViewSet,
                'ReactionEventSeverity')
router.register(r'reason_medication_given_codes',
                ReasonMedicationGivenCodesViewSet,
                'ReasonMedicationGivenCodes')
router.register(r'reason_medication_not_given_codes',
                ReasonMedicationNotGivenCodesViewSet,
                'ReasonMedicationNotGivenCodes')
router.register(r'reference_version_rules',
                ReferenceVersionRulesViewSet,
                'ReferenceVersionRules')
router.register(r'referencerange_meaning',
                ReferencerangeMeaningViewSet,
                'ReferencerangeMeaning')
router.register(r'referralcategory',
                ReferralcategoryViewSet,
                'Referralcategory')
router.register(r'referralstatus',
                ReferralstatusViewSet,
                'Referralstatus')
router.register(r'relationship',
                RelationshipViewSet,
                'Relationship')
router.register(r'remittance_outcome',
                RemittanceOutcomeViewSet,
                'RemittanceOutcome')
router.register(r'required_behavior',
                RequiredBehaviorViewSet,
                'RequiredBehavior')
router.register(r'resource_aggregation_mode',
                ResourceAggregationModeViewSet,
                'ResourceAggregationMode')
router.register(r'resource_slicing_rules',
                ResourceSlicingRulesViewSet,
                'ResourceSlicingRules')
router.register(r'resource_type_link',
                ResourceTypeLinkViewSet,
                'ResourceTypeLink')
router.register(r'resource_types',
                ResourceTypesViewSet,
                'ResourceTypes')
router.register(r'resource_validation_mode',
                ResourceValidationModeViewSet,
                'ResourceValidationMode')
router.register(r'response_code',
                ResponseCodeViewSet,
                'ResponseCode')
router.register(r'restful_conformance_mode',
                RestfulConformanceModeViewSet,
                'RestfulConformanceMode')
router.register(r'restful_interaction',
                RestfulInteractionViewSet,
                'RestfulInteraction')
router.register(r'restful_security_service',
                RestfulSecurityServiceViewSet,
                'RestfulSecurityService')
router.register(r'risk_probability',
                RiskProbabilityViewSet,
                'RiskProbability')
router.register(r'ruleset',
                RulesetViewSet,
                'Ruleset')
router.register(r'search_entry_mode',
                SearchEntryModeViewSet,
                'SearchEntryMode')
router.register(r'search_modifier_code',
                SearchModifierCodeViewSet,
                'SearchModifierCode')
router.register(r'search_param_type',
                SearchParamTypeViewSet,
                'SearchParamType')
router.register(r'search_xpath_usage',
                SearchXpathUsageViewSet,
                'SearchXpathUsage')
router.register(r'audit_source_type',
                AuditSourceTypeViewSet,
                'AuditSourceType')
router.register(r'selection_behavior',
                SelectionBehaviorViewSet,
                'SelectionBehavior')
router.register(r'sequence_type',
                SequenceTypeViewSet,
                'SequenceType')
router.register(r'service_category',
                ServiceCategoryViewSet,
                'ServiceCategory')
router.register(r'service_provision_conditions',
                ServiceProvisionConditionsViewSet,
                'ServiceProvisionConditions')
router.register(r'service_referral_method',
                ServiceReferralMethodViewSet,
                'ServiceReferralMethod')
router.register(r'service_type',
                ServiceTypeViewSet,
                'ServiceType')
router.register(r'icd_10_procedures',
                Icd10ProceduresViewSet,
                'Icd10Procedures')
router.register(r'slotstatus',
                SlotstatusViewSet,
                'Slotstatus')
router.register(r'special_values',
                SpecialValuesViewSet,
                'SpecialValues')
router.register(r'specimen_status',
                SpecimenStatusViewSet,
                'SpecimenStatus')
router.register(r'structure_definition_kind',
                StructureDefinitionKindViewSet,
                'StructureDefinitionKind')
router.register(r'subscription_channel_type',
                SubscriptionChannelTypeViewSet,
                'SubscriptionChannelType')
router.register(r'subscription_status',
                SubscriptionStatusViewSet,
                'SubscriptionStatus')
router.register(r'subscription_tag',
                SubscriptionTagViewSet,
                'SubscriptionTag')
router.register(r'substance_category',
                SubstanceCategoryViewSet,
                'SubstanceCategory')
router.register(r'supplydelivery_type',
                SupplydeliveryTypeViewSet,
                'SupplydeliveryType')
router.register(r'supplyrequest_kind',
                SupplyrequestKindViewSet,
                'SupplyrequestKind')
router.register(r'supplydelivery_status',
                SupplydeliveryStatusViewSet,
                'SupplydeliveryStatus')
router.register(r'supplyrequest_reason',
                SupplyrequestReasonViewSet,
                'SupplyrequestReason')
router.register(r'supplyrequest_status',
                SupplyrequestStatusViewSet,
                'SupplyrequestStatus')
router.register(r'task_performer_type',
                TaskPerformerTypeViewSet,
                'TaskPerformerType')
router.register(r'task_priority',
                TaskPriorityViewSet,
                'TaskPriority')
router.register(r'task_stage',
                TaskStageViewSet,
                'TaskStage')
router.register(r'task_status',
                TaskStatusViewSet,
                'TaskStatus')
router.register(r'testscript_operation_codes',
                TestscriptOperationCodesViewSet,
                'TestscriptOperationCodes')
router.register(r'testscript_profile_destination_types',
                TestscriptProfileDestinationTypesViewSet,
                'TestscriptProfileDestinationTypes')
router.register(r'testscript_profile_origin_types',
                TestscriptProfileOriginTypesViewSet,
                'TestscriptProfileOriginTypes')
router.register(r'transaction_mode',
                TransactionModeViewSet,
                'TransactionMode')
router.register(r'trigger_type',
                TriggerTypeViewSet,
                'TriggerType')
router.register(r'type_derivation_rule',
                TypeDerivationRuleViewSet,
                'TypeDerivationRule')
router.register(r'unknown_content_code',
                UnknownContentCodeViewSet,
                'UnknownContentCode')
router.register(r'vaccination_protocol_dose_status',
                VaccinationProtocolDoseStatusViewSet,
                'VaccinationProtocolDoseStatus')
router.register(r'vaccination_protocol_dose_status_reason',
                VaccinationProtocolDoseStatusReasonViewSet,
                'VaccinationProtocolDoseStatusReason')
router.register(r'variant_state',
                VariantStateViewSet,
                'VariantState')
router.register(r'versioning_policy',
                VersioningPolicyViewSet,
                'VersioningPolicy')
router.register(r'vision_base_codes',
                VisionBaseCodesViewSet,
                'VisionBaseCodes')
router.register(r'vision_eye_codes',
                VisionEyeCodesViewSet,
                'VisionEyeCodes')
router.register(r'xds_relationship_type',
                XdsRelationshipTypeViewSet,
                'XdsRelationshipType')

router.register(r'AcknowledgementCondition',
                AcknowledgementconditionViewSet,
                'Acknowledgementcondition')
router.register(r'AcknowledgementDetailCode',
                AcknowledgementdetailcodeViewSet,
                'Acknowledgementdetailcode')
router.register(r'AcknowledgementDetailType',
                AcknowledgementdetailtypeViewSet,
                'Acknowledgementdetailtype')
router.register(r'AcknowledgementType',
                AcknowledgementtypeViewSet,
                'Acknowledgementtype')
router.register(r'ActClass',
                ActclassViewSet,
                'Actclass')
router.register(r'ActCode',
                ActcodeViewSet,
                'Actcode')
router.register(r'ActExposureLevelCode',
                ActexposurelevelcodeViewSet,
                'Actexposurelevelcode')
router.register(r'ActInvoiceElementModifier',
                ActinvoiceelementmodifierViewSet,
                'Actinvoiceelementmodifier')
router.register(r'ActMood',
                ActmoodViewSet,
                'Actmood')
router.register(r'ActPriority',
                ActpriorityViewSet,
                'Actpriority')
router.register(r'ActReason',
                ActreasonViewSet,
                'Actreason')
router.register(r'ActRelationshipCheckpoint',
                ActrelationshipcheckpointViewSet,
                'Actrelationshipcheckpoint')
router.register(r'ActRelationshipJoin',
                ActrelationshipjoinViewSet,
                'Actrelationshipjoin')
router.register(r'ActRelationshipSplit',
                ActrelationshipsplitViewSet,
                'Actrelationshipsplit')
router.register(r'ActRelationshipSubset',
                ActrelationshipsubsetViewSet,
                'Actrelationshipsubset')
router.register(r'ActRelationshipType',
                ActrelationshiptypeViewSet,
                'Actrelationshiptype')
router.register(r'ActSite',
                ActsiteViewSet,
                'Actsite')
router.register(r'ActStatus',
                ActstatusViewSet,
                'Actstatus')
router.register(r'ActUSPrivacyLaw',
                ActusprivacylawViewSet,
                'Actusprivacylaw')
router.register(r'ActUncertainty',
                ActuncertaintyViewSet,
                'Actuncertainty')
router.register(r'AddressPartType',
                AddressparttypeViewSet,
                'Addressparttype')
router.register(r'AmericanIndianAlaskaNativeLanguages',
                AmericanindianalaskanativelanguagesViewSet,
                'Americanindianalaskanativelanguages')
router.register(r'Calendar',
                CalendarViewSet,
                'Calendar')
router.register(r'CalendarCycle',
                CalendarcycleViewSet,
                'Calendarcycle')
router.register(r'CalendarType',
                CalendartypeViewSet,
                'Calendartype')
router.register(r'Charset',
                CharsetViewSet,
                'Charset')
router.register(r'CodingRationale',
                CodingrationaleViewSet,
                'Codingrationale')
router.register(r'CommunicationFunctionType',
                CommunicationfunctiontypeViewSet,
                'Communicationfunctiontype')
router.register(r'CompressionAlgorithm',
                CompressionalgorithmViewSet,
                'Compressionalgorithm')
router.register(r'Confidentiality',
                ConfidentialityViewSet,
                'Confidentiality')
router.register(r'ContainerCap',
                ContainercapViewSet,
                'Containercap')
router.register(r'ContainerSeparator',
                ContainerseparatorViewSet,
                'Containerseparator')
router.register(r'ContentProcessingMode',
                ContentprocessingmodeViewSet,
                'Contentprocessingmode')
router.register(r'ContextControl',
                ContextcontrolViewSet,
                'Contextcontrol')
router.register(r'DataOperation',
                DataoperationViewSet,
                'Dataoperation')
router.register(r'DeviceAlertLevel',
                DevicealertlevelViewSet,
                'Devicealertlevel')
router.register(r'DocumentCompletion',
                DocumentcompletionViewSet,
                'Documentcompletion')
router.register(r'DocumentStorage',
                DocumentstorageViewSet,
                'Documentstorage')
router.register(r'EducationLevel',
                EducationlevelViewSet,
                'Educationlevel')
router.register(r'EmployeeJobClass',
                EmployeejobclassViewSet,
                'Employeejobclass')
router.register(r'EncounterAdmissionSource',
                EncounteradmissionsourceViewSet,
                'Encounteradmissionsource')
router.register(r'EncounterSpecialCourtesy',
                EncounterspecialcourtesyViewSet,
                'Encounterspecialcourtesy')
router.register(r'EntityClass',
                EntityclassViewSet,
                'Entityclass')
router.register(r'EntityCode',
                EntitycodeViewSet,
                'Entitycode')
router.register(r'EntityDeterminer',
                EntitydeterminerViewSet,
                'Entitydeterminer')
router.register(r'EntityHandling',
                EntityhandlingViewSet,
                'Entityhandling')
router.register(r'EntityNamePartQualifier',
                EntitynamepartqualifierViewSet,
                'Entitynamepartqualifier')
router.register(r'EntityNamePartQualifierR2',
                Entitynamepartqualifierr2ViewSet,
                'Entitynamepartqualifierr2')
router.register(r'EntityNamePartType',
                EntitynameparttypeViewSet,
                'Entitynameparttype')
router.register(r'EntityNamePartTypeR2',
                Entitynameparttyper2ViewSet,
                'Entitynameparttyper2')
router.register(r'EntityNameUse',
                EntitynameuseViewSet,
                'Entitynameuse')
router.register(r'EntityNameUseR2',
                Entitynameuser2ViewSet,
                'Entitynameuser2')
router.register(r'EntityRisk',
                EntityriskViewSet,
                'Entityrisk')
router.register(r'EntityStatus',
                EntitystatusViewSet,
                'Entitystatus')
router.register(r'EquipmentAlertLevel',
                EquipmentalertlevelViewSet,
                'Equipmentalertlevel')
router.register(r'Ethnicity',
                EthnicityViewSet,
                'Ethnicity')
router.register(r'ExposureMode',
                ExposuremodeViewSet,
                'Exposuremode')
router.register(r'GTSAbbreviation',
                GtsabbreviationViewSet,
                'Gtsabbreviation')
router.register(r'GenderStatus',
                GenderstatusViewSet,
                'Genderstatus')
router.register(r'HL7UpdateMode',
                Hl7updatemodeViewSet,
                'Hl7updatemode')
router.register(r'HtmlLinkType',
                HtmllinktypeViewSet,
                'Htmllinktype')
router.register(r'IdentifierReliability',
                IdentifierreliabilityViewSet,
                'Identifierreliability')
router.register(r'IdentifierScope',
                IdentifierscopeViewSet,
                'Identifierscope')
router.register(r'IntegrityCheckAlgorithm',
                IntegritycheckalgorithmViewSet,
                'Integritycheckalgorithm')
router.register(r'LanguageAbilityMode',
                LanguageabilitymodeViewSet,
                'Languageabilitymode')
router.register(r'LanguageAbilityProficiency',
                LanguageabilityproficiencyViewSet,
                'Languageabilityproficiency')
router.register(r'LivingArrangement',
                LivingarrangementViewSet,
                'Livingarrangement')
router.register(r'LocalMarkupIgnore',
                LocalmarkupignoreViewSet,
                'Localmarkupignore')
router.register(r'LocalRemoteControlState',
                LocalremotecontrolstateViewSet,
                'Localremotecontrolstate')
router.register(r'ManagedParticipationStatus',
                ManagedparticipationstatusViewSet,
                'Managedparticipationstatus')
router.register(r'MapRelationship',
                MaprelationshipViewSet,
                'Maprelationship')
router.register(r'MessageWaitingPriority',
                MessagewaitingpriorityViewSet,
                'Messagewaitingpriority')
router.register(r'ModifyIndicator',
                ModifyindicatorViewSet,
                'Modifyindicator')
router.register(r'NullFlavor',
                NullflavorViewSet,
                'Nullflavor')
router.register(r'ObservationInterpretation',
                ObservationinterpretationViewSet,
                'Observationinterpretation')
router.register(r'ObservationMethod',
                ObservationmethodViewSet,
                'Observationmethod')
router.register(r'ObservationValue',
                ObservationvalueViewSet,
                'Observationvalue')
router.register(r'ParticipationFunction',
                ParticipationfunctionViewSet,
                'Participationfunction')
router.register(r'ParticipationMode',
                ParticipationmodeViewSet,
                'Participationmode')
router.register(r'ParticipationSignature',
                ParticipationsignatureViewSet,
                'Participationsignature')
router.register(r'ParticipationType',
                ParticipationtypeViewSet,
                'Participationtype')
router.register(r'PatientImportance',
                PatientimportanceViewSet,
                'Patientimportance')
router.register(r'PaymentTerms',
                PaymenttermsViewSet,
                'Paymentterms')
router.register(r'PersonDisabilityType',
                PersondisabilitytypeViewSet,
                'Persondisabilitytype')
router.register(r'ProbabilityDistributionType',
                ProbabilitydistributiontypeViewSet,
                'Probabilitydistributiontype')
router.register(r'ProcessingID',
                ProcessingidViewSet,
                'Processingid')
router.register(r'ProcessingMode',
                ProcessingmodeViewSet,
                'Processingmode')
router.register(r'QueryParameterValue',
                QueryparametervalueViewSet,
                'Queryparametervalue')
router.register(r'QueryPriority',
                QuerypriorityViewSet,
                'Querypriority')
router.register(r'QueryRequestLimit',
                QueryrequestlimitViewSet,
                'Queryrequestlimit')
router.register(r'QueryResponse',
                QueryresponseViewSet,
                'Queryresponse')
router.register(r'QueryStatusCode',
                QuerystatuscodeViewSet,
                'Querystatuscode')
router.register(r'Race',
                RaceViewSet,
                'Race')
router.register(r'RelationalOperator',
                RelationaloperatorViewSet,
                'Relationaloperator')
router.register(r'RelationshipConjunction',
                RelationshipconjunctionViewSet,
                'Relationshipconjunction')
router.register(r'ReligiousAffiliation',
                ReligiousaffiliationViewSet,
                'Religiousaffiliation')
router.register(r'ResponseLevel',
                ResponselevelViewSet,
                'Responselevel')
router.register(r'ResponseModality',
                ResponsemodalityViewSet,
                'Responsemodality')
router.register(r'ResponseMode',
                ResponsemodeViewSet,
                'Responsemode')
router.register(r'RoleClass',
                RoleclassViewSet,
                'Roleclass')
router.register(r'RoleCode',
                RolecodeViewSet,
                'Rolecode')
router.register(r'RoleLinkStatus',
                RolelinkstatusViewSet,
                'Rolelinkstatus')
router.register(r'RoleLinkType',
                RolelinktypeViewSet,
                'Rolelinktype')
router.register(r'RoleStatus',
                RolestatusViewSet,
                'Rolestatus')
router.register(r'RouteOfAdministration',
                RouteofadministrationViewSet,
                'Routeofadministration')
router.register(r'Sequencing',
                SequencingViewSet,
                'Sequencing')
router.register(r'SetOperator',
                SetoperatorViewSet,
                'Setoperator')
router.register(r'SpecimenType',
                SpecimentypeViewSet,
                'Specimentype')
router.register(r'SubstitutionCondition',
                SubstitutionconditionViewSet,
                'Substitutioncondition')
router.register(r'TableCellHorizontalAlign',
                TablecellhorizontalalignViewSet,
                'Tablecellhorizontalalign')
router.register(r'TableCellScope',
                TablecellscopeViewSet,
                'Tablecellscope')
router.register(r'TableCellVerticalAlign',
                TablecellverticalalignViewSet,
                'Tablecellverticalalign')
router.register(r'TableFrame',
                TableframeViewSet,
                'Tableframe')
router.register(r'TableRules',
                TablerulesViewSet,
                'Tablerules')
router.register(r'TargetAwareness',
                TargetawarenessViewSet,
                'Targetawareness')
router.register(r'TelecommunicationCapabilities',
                TelecommunicationcapabilitiesViewSet,
                'Telecommunicationcapabilities')
router.register(r'TimingEvent',
                TimingeventViewSet,
                'Timingevent')
router.register(r'TransmissionRelationshipTypeCode',
                TransmissionrelationshiptypecodeViewSet,
                'Transmissionrelationshiptypecode')
router.register(r'TribalEntityUS',
                TribalentityusViewSet,
                'Tribalentityus')
router.register(r'VaccineManufacturer',
                VaccinemanufacturerViewSet,
                'Vaccinemanufacturer')
router.register(r'hl7Realm',
                Hl7realmViewSet,
                'Hl7realm')
router.register(r'hl7V3Conformance',
                Hl7v3conformanceViewSet,
                'Hl7v3conformance')
router.register(r'orderableDrugForm',
                OrderabledrugformViewSet,
                'Orderabledrugform')
router.register(r'substanceAdminSubstitution',
                SubstanceadminsubstitutionViewSet,
                'Substanceadminsubstitution')

urlpatterns = router.urls
